/**
 * Key generation for Portable Text blocks/spans/mark definitions.
 *
 * Keys are *not* identity — `@portabletext/markdown` documents that keys are
 * regenerated by parsers, and adjacent spans with identical marks merge. The
 * same contract applies here: keys exist for React lists and block
 * addressing, not as stable row ids. Override with `keyGenerator` if your
 * app needs deterministic keys (e.g. diffing or revisions).
 */
import type { KeyGenerator } from "./types.js";

const ALPHABET = "abcdefghijklmnopqrstuvwxyz0123456789";

/** Default generator: 12-char base-36-ish key, same shape as PT tooling. */
export const randomKey: KeyGenerator = () => {
  let key = "";
  for (let i = 0; i < 12; i += 1) {
    key += ALPHABET[Math.floor(Math.random() * ALPHABET.length)];
  }
  return key;
};
